# Generated by Django 4.2.5 on 2023-09-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=70)),
                ('votos', models.IntegerField(default=0)),
                ('idPergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.pergunta')),
            ],
        ),
    ]
